### ISSUE TITLE
Documentation Release Checklist - Uyuni 2022.03

### ISSUE THREAD

**Issue by jpgrazi** [uyuni-project/uyuni-docs#1582]
## Before Packaging Day

- [ ] Check for previous Uyuni versions in the text, and update where necessary.
- [ ] Check all outstanding pull requests, and ensure everything relevant is merged (and backported where required).
Check with the docs squad coordinator for confirmation.

## Packaging Day:

- [X ] Update entities to the current versions.
- [ ] Cut a new branch from master using syntax `uyuni-YYYY-MM-pages` based on the gh-pages branch.
- [ ] Locally build docs from the release branch and visually check output.
- [ ] Package documentation and push SR to OBS: https://github.com/uyuni-project/uyuni-docs/wiki/publishing-to-obs
- [ ] Notify Release Manager of SR.
- [ ] Release Manager accepts package.
- [ ] Create the PR to publish Uyuni to gh-pages: https://github.com/uyuni-project/uyuni-docs/tree/gh-pages. Add the release engineer as the assignee, and use a label with current Uyuni version. **Do not merge, the release engineer will do it**

## API Docs

- [ ] Obtain API doc RPM
- [ ] Add asciidoc sources to api project
- [ ] Check the diff and verify there were no additions to the navigation links (New API calls)
- [ ] Create a new gh-pages-uyuni-YYYY.MM branch for the API docs and supply Julio with PR

## Release Day:- 
- [ ] When endpoints are live, visually check output.

Hello i follow the legal documentation to update uyuni to its latest packages version. today I found that the repos configured in the uyuni master for the proxies to be updated are outdated. The documentation states to configure the following in the master server:
spacewalk-common-channels opensuse_leap15_3 \
opensuse_leap15_3-non-oss \
opensuse_leap15_3-non-oss-updates \
opensuse_leap15_3-updates \
opensuse_leap15_3-backports-update \
opensuse_leap15_3-sle-updates \
opensuse_leap15_3-uyuni-client \
uyuni-proxy-stable-leap-153

All the process was done as a minor update to the proxy that is supposed to update the packages to the right versions for uyuni to work correctly.... but I found that the packages in those repos don't solve many of the security vulnerabilities reported in our Rapid 7 system. In fact, the uyuni proxy is having one of the highest scores of all the Linux servers.  
I enabled the OS repos configured in the server since its installation, and those really pull the right OS packages that solve the vulnerabilities... but I’m afraid that those packages won't work correctly with the uyuni proxy software. 
Can you point me to the right repositories that have the security vulnerabilities solved and work with uyuni proxy software well?
..or can I continue doing the update as mentioned, with all the repos in the system enabled, without risk to break the uyuni proxy services?

Thanks in advance for your answer/guidance on this. 

Jean.
