### ISSUE TITLE
Documentation Release Checklist - Uyuni 2020.09

### ISSUE THREAD

**Issue by Loquacity** [uyuni-project/uyuni-docs#542]
# Documentation Release Checklist - Uyuni

Use this issue template for documentation releases.

## Before Packaging Day

- [x] Check for previous Uyuni versions in the text, and update where necessary.
- [x] Check all outstanding pull requests, and ensure everything relevant is merged (and backported where required).
Check with the docs squad coordinator for confirmation.

## Packaging Day:

- [x] Update entities to the current versions.
- [x] For Uyuni, cut a new branch from master using syntax `uyuni-YYYY-MM-pages` based on the gh-pages branch. https://github.com/uyuni-project/uyuni-docs/tree/uyuni-2020.09
- [x] Locally build docs from the release branch and visually check output. https://github.com/uyuni-project/uyuni-docs/pull/543
- [x] Package documentation and push SR to OBS: https://github.com/uyuni-project/uyuni-docs/wiki/building-suma-docs#building-suma-obs-packages https://build.opensuse.org/request/show/835198
- [x] Notify Release Manager of SR.
- [x] Release Manager accepts package.

## Release Day:

- [x] Build docs from release branch and visually check output.
- [x] Publish Uyuni to gh-pages: https://github.com/uyuni-project/uyuni-docs/tree/gh-pages. Add Release Manager as the assignee, and use a label with current Uyuni version. https://github.com/uyuni-project/uyuni-docs/pull/550
- [x] When endpoints are live, visually check output.
