### ISSUE TITLE
Documentation Release Checklist - Uyuni 2020.11

### ISSUE THREAD

**Issue by Loquacity** [uyuni-project/uyuni-docs#679]
## Before Packaging Day

- [x] Check for previous Uyuni versions in the text, and update where necessary.
- [x] Check all outstanding pull requests, and ensure everything relevant is merged (and backported where required).
Check with the docs squad coordinator for confirmation.

To be merged:
- [x] https://github.com/SUSE/spacewalk/issues/13106 - CSH (@parlt91 )
- [x] https://github.com/uyuni-project/uyuni-docs/pull/653 - Client Cfg Client edits (@Loquacity )
- [x] https://github.com/uyuni-project/uyuni-docs/pull/669 - Client Cfg Contact Methods (@keichwa )
- [x] https://github.com/uyuni-project/uyuni-docs/pull/674 - Chinese font support (@jcayouette )

## Packaging Day:

- [x] Update entities to the current versions.
- [x] Cut a new branch from master using syntax `uyuni-2020-11-pages` based on the gh-pages branch.
- [x] Locally build docs from the release branch and visually check output.
- [x] Package documentation and push SR to OBS: https://github.com/uyuni-project/uyuni-docs/wiki/publishing-to-obs
- [x] Notify Release Manager of SR.
- [x] Release Manager accepts package.

## Release Day:

- [x] Build docs from release branch and visually check output.
- [x] Publish Uyuni to gh-pages: https://github.com/uyuni-project/uyuni-docs/tree/gh-pages. Add Release Manager as the assignee, and use a label with current Uyuni version.
- [x] When endpoints are live, visually check output.

**Comment by parlt91** [comment]
@Loquacity I don't have the rights necessary to check the checkbox myself. 
- [ ] SUSE/spacewalk#13106 - CSH (@parlt91 ) is done for uyuni
