### ISSUE TITLE
Documentation Release Checklist - Uyuni 2021.02

### ISSUE THREAD

**Issue by Loquacity** [uyuni-project/uyuni-docs#773]
## Before Packaging Day

- [x] Check for previous Uyuni versions in the text, and update where necessary.
- [x] Check all outstanding pull requests, and ensure everything relevant is merged (and backported where required).
Check with the docs squad coordinator for confirmation. (Nothing required to merge, note that the QS:Uyuni guide is not yet enabled, as it's still on tech review. --LKB)

## Packaging Day:

- [x] Update entities to the current versions.
- [x] Cut a new branch from master called `uyuni-2021-01-pages` based on the gh-pages branch.
- [x] Locally build docs from the release branch and visually check output.
- [x] Package documentation and push SR to OBS: https://github.com/uyuni-project/uyuni-docs/wiki/publishing-to-obs
- [x] Notify Release Manager of SR (see https://github.com/uyuni-project/uyuni-project.github.io/pull/33)
- [x] Release Manager accepts package.
- [x] Create the PR to publish Uyuni to gh-pages: https://github.com/uyuni-project/uyuni-docs/tree/gh-pages. Add the release engineer as the assignee, and use a label with current Uyuni version. **Do not merge, the release engineer will do it**

## Release Day:

- [x] Build docs from release branch and visually check output.
- [x] When endpoints are live, visually check output.
